### ISSUE TITLE
error is not properly handel it's loading loading and loading user need to do refresh to fix the loading issue which is not good

### ISSUE THREAD

**Issue by Rishi9868** [Atanu8250/GadgetRambo#87]
https://github.com/Atanu8250/separate-grass-3333/blob/69c06f5f37b4611b41f2c7560f87549bbd6ce82d/components/Login.tsx#L44

**Comment by Atanu8250** [comment]
Sorry, @Rishi9868, actually I tried from my side but I'm not able to find this case when this loading is not stoping..?
If possible, can you please tell me, when it's happening?

**Comment by rajkumar-cmd** [comment]
Sir I am not able to understand the issue properly
